#!/usr/bin/env python
import miniupnpc
u = miniupnpc.UPnP()
u.discoverdelay=200;u.discover();u.selectigd()

p=1;i=0
while p:
  p = u.getgenericportmapping(i) ; i+=1
  if p:
    port,protocol,(toAddr,toPort),desc,x,y,z = p
    print protocol+":"+str(port),"->",toAddr+":"+str(toPort)+"\t"+desc
