#!/usr/bin/env python2
import argparse
import miniupnpc

parser = argparse.ArgumentParser(description='List all current mappings via UPnP.')
parser.add_argument('-d', '--discoverdelay', metavar='delay-in-ms', dest='discoverdelay', default=200, help='If unset, default to 200')
args = parser.parse_args()

u = miniupnpc.UPnP()
u.discoverdelay = args.discoverdelay
u.discover()
u.selectigd()

i = 0
while True:
  p = u.getgenericportmapping(i)
  i += 1
  if p == None:
    break
  
  port, protocol, (address, intport), desc, x, y, z = p
  print protocol + ":" + str(port), "->" , address + ":" + str(intport) + "\t" + desc
