#!/usr/bin/env python2
import argparse
import miniupnpc
import urllib2

parser = argparse.ArgumentParser(description='Get the current date reported via UPnP.')
parser.add_argument('-d', '--discoverdelay', metavar='delay-in-ms', dest='discoverdelay', default=200, help='If unset, default to 200')
args = parser.parse_args()

u = miniupnpc.UPnP()
u.discoverdelay = args.discoverdelay
u.discover()
u.selectigd()

date = urllib2.urlopen("http://"+u.externalipaddress()).headers["Date"]
if date.endswith("GMT"):
    # some routers have local time but incorrectly call it GMT
    date = date[:-3].rstrip()

print date.replace(", "," ")
