#!/usr/bin/env python2
import argparse
import miniupnpc

parser = argparse.ArgumentParser(description='Print the external IP address reported via UPnP.')
parser.add_argument('-d', '--discoverdelay', metavar='delay-in-ms', dest='discoverdelay', default=200, help='If unset, default to 200')
args = parser.parse_args()

u = miniupnpc.UPnP()
u.discoverdelay = args.discoverdelay
u.discover()
u.selectigd()

print u.externalipaddress()
