#!/usr/bin/env python
import miniupnpc
u = miniupnpc.UPnP()
u.discoverdelay=200;u.discover();u.selectigd()

import urllib2
date = urllib2.urlopen("http://"+u.externalipaddress()).headers["Date"]
if date.endswith("GMT"): date=date[:-3].rstrip() # some routers have local time but incorrectly call it GMT
print date.replace(", "," ")
