#!/usr/bin/env python2
import argparse
import sys
import miniupnpc

parser = argparse.ArgumentParser(description='Delete a port mapping from the UPnP server.')
parser.add_argument('-p', '--port', required=True, metavar='port', dest='port', type=int, help='The external port number')
parser.add_argument('-r', '--protocol', metavar='protocol', dest='protocol', default='', help='If unset, defaults to TCP')
parser.add_argument('-d', '--discoverdelay', metavar='delay-in-ms', dest='discoverdelay', default=200, help='If unset, default to 200')
args = parser.parse_args()

u = miniupnpc.UPnP()
u.discoverdelay = args.discoverdelay
u.discover()
u.selectigd()

u.deleteportmapping(args.port, args.protocol)
